export const FETCH_CART = 'FETCH_CART';
export const FETCH_CART_FAILED = 'FETCH_CART_FAILED';
export const FETCH_CART_SUCCEEDED = 'FETCH_CART_SUCCEEDED';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const ADD_ITEM_TO_CART_FAILED = 'ADD_ITEM_TO_CART_FAILED';
export const ADD_ITEM_TO_CART_SUCCEEDED = 'ADD_ITEM_TO_CART_SUCCEEDED';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ITEM_FROM_CART_FAILED = 'REMOVE_ITEM_FROM_CART_FAILED';
export const REMOVE_ITEM_FROM_CART_SUCCEEDED = 'REMOVE_ITEM_FROM_CART_SUCCEEDED';
